export const FETCH_NEAR_BALANCE_PENDING = 'FETCH_NEAR_BALANCE_PENDING';
export const FETCH_NEAR_BALANCE_SUCCESS = 'FETCH_NEAR_BALANCE_SUCCESS';
export const FETCH_NEAR_BALANCE_ERROR = 'FETCH_NEAR_BALANCE_ERROR';

export const FETCH_WNEAR_BALANCE_PENDING = 'FETCH_WNEAR_BALANCE_PENDING';
export const FETCH_WNEAR_BALANCE_SUCCESS = 'FETCH_WNEAR_BALANCE_SUCCESS';
export const FETCH_WNEAR_BALANCE_ERROR = 'FETCH_WNEAR_BALANCE_ERROR';

export const SET_NEAR_BALANCE_INTO_INPUT = 'SET_NEAR_BALANCE_INTO_INPUT'
export const SET_IS_WRAP = 'SET_IS_WRAP'

export const DO_WRAP_NEAR = 'DO_WRAP_NEAR'
